package jogoanatomia.telas;

import java.awt.BorderLayout;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import jogoanatomia.entidades.Estudos;
import java.util.ArrayList;
import javax.media.j3d.*;
import javax.swing.JFrame;
import javax.vecmath.Color3f;
import javax.vecmath.Point3d;
import jogoanatomia.entidades.Orgao;
import jogoanatomia.loader.CarregaObj;
import jogoanatomia.loader.CarregaStereo;

public class Estudar extends javax.swing.JFrame {

    static Estudar singleton;
    ArrayList<Estudos> conteudos;
    int contaConteudo;
    private Canvas3D c;
    public static VirtualUniverse u;
    public Locale myLocale;
    
    public static Estudar getInstance(){
        if (singleton==null){
            singleton=new Estudar();
        }
        return singleton;
    }

    public ArrayList<Estudos> getConteudos() {
        return conteudos;
    }

    public void setConteudos(ArrayList<Estudos> conteudos) {
        this.conteudos = conteudos;
    }
    
    public void iniciaEstudos(){
        contaConteudo=0;
        jLpagina.setText((contaConteudo+1)+"/"+conteudos.size());
        jLnivel.setText(conteudos.get(contaConteudo).getNivel()+"");
        jTAconteudo.setText(conteudos.get(contaConteudo).getConteudo());
        int idOrgao=conteudos.get(0).getIdOrgao();
        Orgao orgao=Orgao.getOrgaoPorId(idOrgao).get(0);
        jLorgao.setText(orgao.getNome());
        //colocar malha no panel --> orgao.getMalha();
        jBanterior.setEnabled(false);
        jBproximo.setEnabled(true);
        GraphicsConfigTemplate3D g3d = new GraphicsConfigTemplate3D();
	GraphicsEnvironment ge = GraphicsEnvironment
			.getLocalGraphicsEnvironment();
	GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
	GraphicsConfiguration gcn = defaultScreen.getBestConfiguration(g3d);
	c = new Canvas3D(gcn);
        // construcao do universo
        u = new VirtualUniverse();
        myLocale = new Locale(u);
            CarregaObj CarregaObj = new CarregaObj();
        CarregaObj.setFile("./"+orgao.getNome().toLowerCase());
        myLocale.addBranchGraph(CarregaObj.createSceneGraph());
        myLocale.addBranchGraph(CarregaObj.branchGroupLeft(c));
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout(10, 0));
        jPanel1.add(c);
        jPanel1.updateUI();
        // Background
        BranchGroup brbg = new BranchGroup();
        BoundingSphere bounds = new BoundingSphere(new Point3d(0.0, 0.0, 0.0),
                100);
        Color3f bgColor = new Color3f(0.0f, 0.7f, 1.0f);
        Background backg = new Background(bgColor);
        backg.setApplicationBounds(bounds);
        brbg.addChild(backg);
        myLocale.addBranchGraph(brbg);

    }

    /**
     * Creates new form Estudar
     */
    public Estudar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAconteudo = new javax.swing.JTextArea();
        jBanterior = new javax.swing.JButton();
        jBproximo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLpagina = new javax.swing.JLabel();
        jLorgao = new javax.swing.JLabel();
        jLnivel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTBestereoscopia = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BodyGame - Estudar");
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(575, 610));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTAconteudo.setColumns(20);
        jTAconteudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTAconteudo.setLineWrap(true);
        jTAconteudo.setRows(5);
        jTAconteudo.setWrapStyleWord(true);
        jTAconteudo.setEnabled(false);
        jScrollPane1.setViewportView(jTAconteudo);
        jTAconteudo.setLineWrap(true);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 530, 100));

        jBanterior.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBanterior.setForeground(new java.awt.Color(102, 0, 0));
        jBanterior.setText("Anterior");
        jBanterior.setEnabled(false);
        jBanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jBanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jBproximo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBproximo.setForeground(new java.awt.Color(102, 0, 0));
        jBproximo.setText("Próximo");
        jBproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBproximoActionPerformed(evt);
            }
        });
        getContentPane().add(jBproximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Estudar - ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Página:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLpagina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLpagina.setText("-/10");
        getContentPane().add(jLpagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLorgao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLorgao.setForeground(new java.awt.Color(153, 0, 0));
        jLorgao.setText("Orelha");
        getContentPane().add(jLorgao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLnivel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLnivel.setText("-");
        getContentPane().add(jLnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nível:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 530, 290));

        jTBestereoscopia.setText("ON");
        jTBestereoscopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBestereoscopiaActionPerformed(evt);
            }
        });
        getContentPane().add(jTBestereoscopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Estereoscopia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogoanatomia/telas/images/fundo_estudar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBproximoActionPerformed
        contaConteudo++;
        jLpagina.setText((contaConteudo + 1) + "/" + conteudos.size());
        jBanterior.setEnabled(true);
        jLnivel.setText(conteudos.get(contaConteudo).getNivel() + "");
        jTAconteudo.setText(conteudos.get(contaConteudo).getConteudo());
        if (contaConteudo == conteudos.size() - 1) {
            jBproximo.setEnabled(false);
        }
    }//GEN-LAST:event_jBproximoActionPerformed

    private void jTBestereoscopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBestereoscopiaActionPerformed
        int idOrgao=conteudos.get(0).getIdOrgao();
        Orgao orgao=Orgao.getOrgaoPorId(idOrgao).get(0);
        GraphicsConfigTemplate3D g3d = new GraphicsConfigTemplate3D();
	GraphicsEnvironment ge = GraphicsEnvironment
			.getLocalGraphicsEnvironment();
	GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
	GraphicsConfiguration gcn = defaultScreen.getBestConfiguration(g3d);
	c = new Canvas3D(gcn);
        // construcao do universo
        u = new VirtualUniverse();
        myLocale = new Locale(u);
            CarregaStereo CarregaObj = new CarregaStereo();
        CarregaObj.setFileName("./"+orgao.getNome().toLowerCase());
        myLocale.addBranchGraph(CarregaObj.createSceneGraph());
        myLocale.addBranchGraph(CarregaObj.branchGroupLeft(c));
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout(10, 0));
        jPanel1.add(c);
        jPanel1.updateUI();
        // Background
        BranchGroup brbg = new BranchGroup();
        BoundingSphere bounds = new BoundingSphere(new Point3d(0.0, 0.0, 0.0),
                400);
        Color3f bgColor = new Color3f(0f, 0f, 0f);
        Background backg = new Background(bgColor);
        backg.setApplicationBounds(bounds);
        brbg.addChild(backg);
        myLocale.addBranchGraph(brbg);
    }//GEN-LAST:event_jTBestereoscopiaActionPerformed

    private void jBanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanteriorActionPerformed
        contaConteudo--;
        jLpagina.setText((contaConteudo + 1) + "/" + conteudos.size());
        jBproximo.setEnabled(true);
        jLnivel.setText(conteudos.get(contaConteudo).getNivel() + "");
        jTAconteudo.setText(conteudos.get(contaConteudo).getConteudo());
        if (contaConteudo == 0) {
            jBanterior.setEnabled(false);
        }
    }//GEN-LAST:event_jBanteriorActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanterior;
    private javax.swing.JButton jBproximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLnivel;
    private javax.swing.JLabel jLorgao;
    private javax.swing.JLabel jLpagina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAconteudo;
    private javax.swing.JToggleButton jTBestereoscopia;
    // End of variables declaration//GEN-END:variables
}
