package jogoanatomia.telas;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import jogoanatomia.entidades.User;
import jogoanatomia.services.UserService;
import jogoanatomia.services.UserServiceImpl;
import net.sourceforge.napkinlaf.NapkinLookAndFeel;

public class TelaInicial extends javax.swing.JFrame {
    private UserService userService;

    public TelaCadastro telaDeCadastro;
    
    public TelaPersonagemOrgaos telaPersoganemOrgao;
        
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        try{
            UIManager.setLookAndFeel(new NapkinLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        }catch(Exception e ){
            System.err.println(e.toString());
        }
        userService = new UserServiceImpl();
        telaDeCadastro = new TelaCadastro();
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEntrar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jTextSenha = new javax.swing.JPasswordField();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextLogin1 = new javax.swing.JTextField();
        jButtonCadastro = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BodyGame");
        setBounds(new java.awt.Rectangle(200, 50, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(590, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEntrar.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(153, 0, 0));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 130, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("BodyGame");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 580, 50));

        jTextSenha.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jTextSenha.setToolTipText("Insira a senha");
        getContentPane().add(jTextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, 40));

        jLabelLogin.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jLabelLogin.setText("Login:");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabelSenha.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 60, 20));

        jTextLogin1.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jTextLogin1.setToolTipText("Insira o login");
        getContentPane().add(jTextLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 40));

        jButtonCadastro.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButtonCadastro.setForeground(new java.awt.Color(153, 0, 0));
        jButtonCadastro.setText("Cadastre-se");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, -1));

        jLabelMessage.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brain.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spleen.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        jLabelMessage.setText("");
        String login  = jTextLogin1.getText();
        String senha = jTextSenha.getText();
        if(login==null || login.isEmpty()){
            jLabelMessage.setText("Insira o login");
            
        }else if(senha==null || senha.isEmpty()){
            jLabelMessage.setText("Insira a senha");
        }else{
            User user = userService.login(login, senha);

            if(user != null) {
                SessionStore.setLoggedUser(user);

                this.dispose();

                if(user.getCharacter() == null) {
                    new TelaSelecionaPersonagens().setVisible(true);
                } else {
                    telaPersoganemOrgao = new TelaPersonagemOrgaos();
                    telaPersoganemOrgao.setVisible(true);
                }
            } else {
                jLabelMessage.setText("Login ou senha inválidos!");
            }
        }
           
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        this.dispose();
        telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCadastro;
    public javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLogin;
    public javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTitulo;
    public javax.swing.JTextField jTextLogin1;
    public javax.swing.JPasswordField jTextSenha;
    // End of variables declaration//GEN-END:variables
}
