package jogoanatomia.telas;

import java.awt.BorderLayout;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.ArrayList;
import java.util.List;

import javax.media.j3d.*;
import javax.swing.JFrame;
import javax.vecmath.Color3f;
import javax.vecmath.Point3d;

import jogoanatomia.entidades.Organ;
import jogoanatomia.entidades.Study;
import jogoanatomia.loader.CarregaObj;
import jogoanatomia.loader.CarregaStereo;
import jogoanatomia.services.StudyServiceImpl;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;

public class TelaEstudar extends javax.swing.JFrame {

    public CarregaObj carregaObj;
    
    public CarregaStereo carregaStereo;
    
    public List<Study> conteudos;
    
    private StudyServiceImpl studyServiceImpl;

    public int contaConteudo;
    
    private Organ orgao;
    
    private TelaEscolheJogo windowJogos;

    /**
     * Creates new form Estudar
     */
    public TelaEstudar() {
        initComponents();
        
    }
    
    public void iniciar(){
        studyServiceImpl = new StudyServiceImpl();
        conteudos = studyServiceImpl.listByOrganId(orgao.getId());
        jLabel1.setText(orgao.getName());
        jTextAreaConteudo.setLineWrap(true);
        jTextAreaConteudo.setWrapStyleWord(true);
        jTextAreaConteudo.setText(conteudos.get(0).getContent());
        carregaObj = new CarregaObj();
        String file = orgao.getImageFileName();
        carregaObj.setFile(file);
        Canvas3D c = carregaObj.carregaOrgao();
        atualizaPanel(c);        
    }
    
    public void atualizaPanel(Canvas3D c){
        jPanelOrgao.removeAll();
        jPanelOrgao.setLayout(new BorderLayout(10, 0));
        jPanelOrgao.add(c);
        jPanelOrgao.updateUI();
    }

    public Organ getOrgao() {
        return orgao;
    }

    public void setOrgao(Organ orgao) {
        this.orgao = orgao;
    }
    
    private void disposeAndBackToOrganSelection() {
        TelaPersonagemOrgaos personagemOrgaos = new TelaPersonagemOrgaos();
        this.dispose();
        personagemOrgaos.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelOrgao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConteudo = new javax.swing.JTextArea();
        jButtonAnterior = new javax.swing.JButton();
        jButtonAnterior.setEnabled(false);
        jButtonJogar = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonStereo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BodyGame - Estudar");
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(575, 610));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("BodyGame");

        jTextAreaConteudo.setColumns(20);
        jTextAreaConteudo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextAreaConteudo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConteudo);

        jButtonAnterior.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jButtonAnterior.setForeground(new java.awt.Color(153, 0, 0));
        jButtonAnterior.setText("<< Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonJogar.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jButtonJogar.setForeground(new java.awt.Color(153, 0, 0));
        jButtonJogar.setText("Jogar");
        jButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarActionPerformed(evt);
            }
        });

        jButtonProximo.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jButtonProximo.setForeground(new java.awt.Color(153, 0, 0));
        jButtonProximo.setText("Próximo >>");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Orgao");

        jRadioButtonStereo.setText("Stereoscopia");
        jRadioButtonStereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStereoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabelTitulo, GroupLayout.PREFERRED_SIZE, 580, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(31)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 429, GroupLayout.PREFERRED_SIZE)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jButtonAnterior)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(jButtonProximo)))
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jButtonJogar)
        							.addGap(19))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jPanelOrgao, GroupLayout.PREFERRED_SIZE, 525, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jRadioButtonStereo)
        								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
        							.addGap(0, 36, Short.MAX_VALUE)))))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jLabelTitulo, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jPanelOrgao, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jRadioButtonStereo)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButtonJogar))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonAnterior)
        				.addComponent(jButtonProximo))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
    	if (contaConteudo > 0) {
    	contaConteudo--;
        jButtonProximo.setEnabled(true);
        jTextAreaConteudo.setText(conteudos.get(contaConteudo).getContent());
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarActionPerformed
        //telaEscolheJogo = new EscolheJogo();
        //telaEscolheJogo.orgao = orgao;
        windowJogos = new TelaEscolheJogo(orgao);
        this.dispose();
        windowJogos.setVisible(true);
    }//GEN-LAST:event_jButtonJogarActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
    	if (contaConteudo < conteudos.size() -1) {
    	contaConteudo++;
        jButtonAnterior.setEnabled(true);
        jTextAreaConteudo.setText(conteudos.get(contaConteudo).getContent());            
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jRadioButtonStereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStereoActionPerformed
        carregaStereo = new CarregaStereo();
        String file = orgao.getImageFileName();
        carregaStereo.setFileName(file);
        atualizaPanel(carregaStereo.carregaObjeto());
    }//GEN-LAST:event_jRadioButtonStereoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        disposeAndBackToOrganSelection();
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAnterior;
    public javax.swing.JButton jButtonJogar;
    public javax.swing.JButton jButtonProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelOrgao;
    private javax.swing.JRadioButton jRadioButtonStereo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConteudo;
    // End of variables declaration//GEN-END:variables
}
